# Application Information
APP_NAME = "AnyKrowd Onboarding QR Generator"
APP_VERSION = "1.0.0"
APP_AUTHOR = "AnyKrowd Development Team"

# Multi-language Support
SUPPORTED_LANGUAGES = {
    'nl': 'Nederlands',
    'en': 'English', 
    'fr': 'Français',
    'es': 'Español'
}

# Translations for templates
TRANSLATIONS = {
    'en': {
        'configuration_overview': 'CONFIGURATION OVERVIEW',
        'user_overview': 'USER OVERVIEW',
        'page': 'Page',
        'of': 'of',
        'user_configuration': 'USER CONFIGURATION',
        'currency_configuration': 'CURRENCY CONFIGURATION',
        'topup_manual': 'TOP-UP MANUAL',
        'whatsapp_group': 'WhatsApp Group Configuration',
        'has_whatsapp': 'Is there a WhatsApp group for this event? (y/n):',
        'enter_whatsapp': 'Enter the WhatsApp group link:',
        'whatsapp_set': 'WhatsApp group set:',
        'no_whatsapp': 'No WhatsApp group configured',
        'no_whatsapp_link': 'No WhatsApp link provided',
        'yes_options': ['y', 'yes'],
        'no_options': ['n', 'no'],
        # PDF Template Translations
        'cash_configuration': 'CASH CONFIGURATION',
        'device_configuration': 'Device Configuration',
        'installation_instructions': 'Installation Instructions',
        'event': 'Event',
        'location': 'Location',
        'sales': 'Sales',
        'roles': 'Roles',
        'payment_methods': 'Payment methods',
        'no_roles_specified': 'No roles specified',
        'step1': '1 - Open StaffX MC',
        'step2': '2 - Click on ONBOARDING QR',
        'step3': '3 - Use camera - and point to the QR code above',
        'step4': '4 - Login with ClientX-QR',
        'step5': '5 - Open the event application on your smartphone',
        'step6': '6 - Open the Payment QR',
        'step7': '7 - Scan with the cash register device - the QR code on your phone',
        'whatsapp_support': 'Having problems - contact us via WhatsApp',
        'whatsapp_support_detail': 'and send us a video or photo of the problem',
        # Terminal Interface Translations
        'cache_cleared': 'Python cache cleared and modules reloaded',
        'cache_warning': 'Warning: Cache clearing encountered an issue',
        'cache_continue': 'This won\'t affect functionality, continuing...',
        'testing_db': 'Testing database connectivity...',
        'db_issue_detected': 'DATABASE CONNECTIVITY ISSUE DETECTED',
        'db_issue_message': 'The application may not function properly due to network issues.',
        'possible_solutions': 'Possible solutions:',
        'check_internet': '1. Check your internet connection',
        'check_vpn': '2. Ensure VPN is connected (if required)',
        'check_aws': '3. Check if AWS RDS is accessible from your location',
        'contact_admin': '4. Contact your network administrator',
        'continue_anyway': 'Do you want to continue anyway? (y/n):',
        'operation_cancelled': 'Operation cancelled due to connectivity issues',
        'continuing_limited': 'Continuing with limited functionality...',
        'enter_tenant_slug': 'Enter the tenant slug:',
        'tenant_slug_required': 'Error: Tenant slug is required',
        'process_interrupted': 'Process interrupted by user',
        'unexpected_error': 'Unexpected error',
        'searching_tenant': 'Searching for tenant with slug',
        'domain_found': 'Domain found',
        'tenant_id_found': 'Tenant ID',
        'tenant_variable': 'Tenant variable',
        'no_exact_match': 'No exact match found for slug',
        'similar_tenants': 'Found {count} similar tenant(s):',
        'select_option': 'Select option',
        'manual_tenant_setup': 'Manual tenant setup',
        'cancel': 'Cancel',
        'operation_cancelled_user': 'Operation cancelled',
        'no_similar_tenants': 'No similar tenants found for',
        'manual_setup_header': 'Manual Tenant Setup',
        'provide_tenant_info': 'Please provide the tenant information manually:',
        'enter_tenant_id': 'Enter tenant ID:',
        'tenant_id_required': 'Tenant ID is required',
        'enter_domain': 'Enter domain (e.g., summercamp-2025.com):',
        'domain_required': 'Domain is required',
        'domain_incomplete': 'Domain \'{domain}\' seems incomplete. Use \'{suggested}\' instead? (y/n):',
        'manual_setup_complete': 'Manual tenant setup complete:',
        'db_warning': 'Warning: Could not connect to tenant database',
        'db_warning_message': 'This may cause issues when retrieving onboarding QRs',
        'continue_anyway_question': 'Continue anyway? (y/n):',
        'db_accessible': 'Tenant database \'{db}\' is accessible',
        'language_selection': 'Language Selection',
        'available_languages': 'Available languages:',
        'select_language': 'Select language',
        'selected_language': 'Selected language',
        'retrieving_qrs': 'Retrieving onboarding QRs for tenant',
        'qrs_found': 'Found {count} onboarding QR(s)',
        'available_qrs': 'Available Onboarding QRs',
        'location': 'Location',
        'sales': 'Sales',
        'event': 'Event',
        'roles': 'Roles',
        'payment_methods': 'Payment methods',
        'qr_code': 'QR Code',
        'template_options': 'Template Options',
        'app_onboarding_qr': '1. Application Onboarding QR',
        'guest_onboarding_qr': '2. Guest User Onboarding QR',
        'select_template': 'Select template type (1 or 2):',
        'enter_1_or_2': 'Enter 1 or 2',
        'enter_valid_number': 'Enter a valid number',
        'generating_app_qrs': 'Generating Application Onboarding QR codes...',
        'multipage_pdf_generated': 'Multi-page PDF generated',
        'contains_pages': 'Contains {count} onboarding QR pages',
        'whatsapp_qr_added': 'WhatsApp QR code added',
        'error_generating_pdf': 'Error generating multi-page QR PDF',
        'generating_guest_qrs': 'Generating Guest User Onboarding QR codes...',
        'searching_user_data': 'Searching for user data based on onboarding names...',
        'user_found': 'User found for',
        'no_user_found': 'No user found for',
        'expected_email': 'expected email',
        'multipage_guest_pdf': 'Multi-page guest PDF generated',
        'guest_qr_pages': 'Contains {count} guest QR pages',
        'error_generating_guest_pdf': 'Error generating multi-page guest QR PDF',
        'import_file_created': 'Import file created for {count} missing users',
        'fill_user_data': 'Fill in the user data and restart the process once ready',
        'import_file_generated': 'Created import file',
        'fill_missing_info': 'Please fill in the missing user information and save the file',
        'missing_dependency': 'Missing dependency',
        'install_requirements': 'Please run: pip install -r requirements.txt',
        'critical_error': 'Critical error',
        'check_config': 'Please check your configuration and try again',
        # Overview Page Translations
        'event_label': 'EVENT:',
        'start_label': 'Start:',
        'end_label': 'Einde:',
        'refund_start_label': 'Refund Start:',
        'refund_end_label': 'Refund Einde:',
        'total_configurations': 'TOTAAL CONFIGURATIES:',
        'name_header': 'NAAM',
        'roles_header': 'ROLES',
        'payment_header': 'PAYMENT',
        'location_header': 'LOCATION',
        'status_header': 'STATUS',
        'user_header': 'USER'
    },
    'nl': {
        'configuration_overview': 'CONFIGURATIE OVERZICHT',
        'user_overview': 'GEBRUIKERS OVERZICHT',
        'page': 'Pagina',
        'of': 'van',
        'user_configuration': 'GEBRUIKER CONFIGURATIE',
        'currency_configuration': 'VALUTA CONFIGURATIE',
        'topup_manual': 'OPWAARDEREN HANDLEIDING',
        'whatsapp_group': 'WhatsApp Groep Configuratie',
        'has_whatsapp': 'Is er een WhatsApp groep voor dit event? (j/n):',
        'enter_whatsapp': 'Voer de WhatsApp groep link in:',
        'whatsapp_set': 'WhatsApp groep ingesteld:',
        'no_whatsapp': 'Geen WhatsApp groep geconfigureerd',
        'no_whatsapp_link': 'Geen WhatsApp link opgegeven',
        'yes_options': ['j', 'ja'],
        'no_options': ['n', 'nee'],
        # PDF Template Translations
        'cash_configuration': 'KASSA CONFIGURATIE',
        'device_configuration': 'Toestel Configuratie',
        'installation_instructions': 'Installatie Instructies',
        'event': 'Evenement',
        'location': 'Locatie',
        'sales': 'Sales',
        'roles': 'Rollen',
        'payment_methods': 'Betaalmethodes',
        'no_roles_specified': 'Geen rollen gespecifieerd',
        'step1': '1 - Open StaffX MC',
        'step2': '2 - Klik op ONBOARDING QR',
        'step3': '3 - Use camera - en richt je op de bovenstaande QR code',
        'step4': '4 - Login met ClientX-QR',
        'step5': '5 - Open de applicatie van het evenement op jouw smartphone',
        'step6': '6 - Open de Payment QR',
        'step7': '7 - Scan met het kassa toestel - de QR code op jouw gsm',
        'whatsapp_support': 'Heb je problemen - contacteer ons via WhatsApp',
        'whatsapp_support_detail': 'en stuur ons een video of foto van het probleem',
        # Terminal Interface Translations
        'cache_cleared': 'Python cache opgeschoond en modules hergeladen',
        'cache_warning': 'Waarschuwing: Cache opschonen heeft een probleem ondervonden',
        'cache_continue': 'Dit heeft geen invloed op de functionaliteit, doorgaan...',
        'testing_db': 'Database connectiviteit testen...',
        'db_issue_detected': 'DATABASE CONNECTIVITEIT PROBLEEM GEDETECTEERD',
        'db_issue_message': 'De applicatie werkt mogelijk niet goed door netwerkproblemen.',
        'possible_solutions': 'Mogelijke oplossingen:',
        'check_internet': '1. Controleer je internetverbinding',
        'check_vpn': '2. Zorg ervoor dat VPN verbonden is (indien vereist)',
        'check_aws': '3. Controleer of AWS RDS toegankelijk is vanaf jouw locatie',
        'contact_admin': '4. Neem contact op met je netwerkbeheerder',
        'continue_anyway': 'Wil je toch doorgaan? (j/n):',
        'operation_cancelled': 'Operatie geannuleerd vanwege connectiviteitsproblemen',
        'continuing_limited': 'Doorgaan met beperkte functionaliteit...',
        'enter_tenant_slug': 'Voer de tenant slug in:',
        'tenant_slug_required': 'Fout: Tenant slug is vereist',
        'process_interrupted': 'Proces onderbroken door gebruiker',
        'unexpected_error': 'Onverwachte fout',
        'searching_tenant': 'Zoeken naar tenant met slug',
        'domain_found': 'Domein gevonden',
        'tenant_id_found': 'Tenant ID',
        'tenant_variable': 'Tenant variabele',
        'no_exact_match': 'Geen exacte overeenkomst gevonden voor slug',
        'similar_tenants': '{count} vergelijkbare tenant(s) gevonden:',
        'select_option': 'Selecteer optie',
        'manual_tenant_setup': 'Handmatige tenant setup',
        'cancel': 'Annuleren',
        'operation_cancelled_user': 'Operatie geannuleerd',
        'no_similar_tenants': 'Geen vergelijkbare tenants gevonden voor',
        'manual_setup_header': 'Handmatige Tenant Setup',
        'provide_tenant_info': 'Geef de tenant informatie handmatig op:',
        'enter_tenant_id': 'Voer tenant ID in:',
        'tenant_id_required': 'Tenant ID is vereist',
        'enter_domain': 'Voer domein in (bijv. summercamp-2025.com):',
        'domain_required': 'Domein is vereist',
        'domain_incomplete': 'Domein \'{domain}\' lijkt onvolledig. \'{suggested}\' gebruiken? (j/n):',
        'manual_setup_complete': 'Handmatige tenant setup voltooid:',
        'db_warning': 'Waarschuwing: Kon niet verbinden met tenant database',
        'db_warning_message': 'Dit kan problemen veroorzaken bij het ophalen van onboarding QRs',
        'continue_anyway_question': 'Toch doorgaan? (j/n):',
        'db_accessible': 'Tenant database \'{db}\' is toegankelijk',
        'language_selection': 'Taal Selectie',
        'available_languages': 'Beschikbare talen:',
        'select_language': 'Selecteer taal',
        'selected_language': 'Geselecteerde taal',
        'retrieving_qrs': 'Onboarding QRs ophalen voor tenant',
        'qrs_found': '{count} onboarding QR(s) gevonden',
        'available_qrs': 'Beschikbare Onboarding QRs',
        'location': 'Locatie',
        'sales': 'Sales',
        'event': 'Evenement',
        'roles': 'Rollen',
        'payment_methods': 'Betaalmethodes',
        'qr_code': 'QR Code',
        'template_options': 'Template Opties',
        'app_onboarding_qr': '1. Applicatie Onboarding QR',
        'guest_onboarding_qr': '2. Gast Gebruiker Onboarding QR',
        'select_template': 'Selecteer template type (1 of 2):',
        'enter_1_or_2': 'Voer 1 of 2 in',
        'enter_valid_number': 'Voer een geldig nummer in',
        'generating_app_qrs': 'Genereren van Applicatie Onboarding QR codes...',
        'multipage_pdf_generated': 'Multi-page PDF gegenereerd',
        'contains_pages': 'Bevat {count} onboarding QR pagina\'s',
        'whatsapp_qr_added': 'WhatsApp QR code toegevoegd',
        'error_generating_pdf': 'Fout bij genereren multi-page QR PDF',
        'generating_guest_qrs': 'Genereren van Gast Gebruiker Onboarding QR codes...',
        'searching_user_data': 'Zoeken naar gebruikersgegevens op basis van onboarding namen...',
        'user_found': 'Gebruiker gevonden voor',
        'no_user_found': 'Geen gebruiker gevonden voor',
        'expected_email': 'verwachte email',
        'multipage_guest_pdf': 'Multi-page gast PDF gegenereerd',
        'guest_qr_pages': 'Bevat {count} gast QR pagina\'s',
        'error_generating_guest_pdf': 'Fout bij genereren multi-page gast QR PDF',
        'import_file_created': 'Import bestand aangemaakt voor {count} ontbrekende gebruikers',
        'fill_user_data': 'Vul de gebruikersgegevens in en start het proces opnieuw zodra het klaar is',
        'import_file_generated': 'Import bestand aangemaakt',
        'fill_missing_info': 'Vul de ontbrekende gebruikersinformatie in en sla het bestand op',
        'missing_dependency': 'Ontbrekende afhankelijkheid',
        'install_requirements': 'Voer uit: pip install -r requirements.txt',
        'critical_error': 'Kritieke fout',
        'check_config': 'Controleer je configuratie en probeer opnieuw',
        # Overview Page Translations
        'event_label': 'EVENT:',
        'start_label': 'Start:',
        'end_label': 'Einde:',
        'refund_start_label': 'Refund Start:',
        'refund_end_label': 'Refund Einde:',
        'total_configurations': 'TOTAAL CONFIGURATIES:',
        'name_header': 'NAAM',
        'roles_header': 'ROLLEN',
        'payment_header': 'BETALING',
        'location_header': 'LOCATIE',
        'status_header': 'STATUS',
        'user_header': 'GEBRUIKER'
    },
    'fr': {
        'configuration_overview': 'APERÇU DE CONFIGURATION',
        'user_overview': 'APERÇU DES UTILISATEURS',
        'page': 'Page',
        'of': 'de',
        'user_configuration': 'CONFIGURATION UTILISATEUR',
        'currency_configuration': 'CONFIGURATION DE DEVISE',
        'topup_manual': 'MANUEL DE RECHARGE',
        'whatsapp_group': 'Configuration du Groupe WhatsApp',
        'has_whatsapp': 'Y a-t-il un groupe WhatsApp pour cet événement? (o/n):',
        'enter_whatsapp': 'Entrez le lien du groupe WhatsApp:',
        'whatsapp_set': 'Groupe WhatsApp configuré:',
        'no_whatsapp': 'Pas de groupe WhatsApp configuré',
        'no_whatsapp_link': 'Aucun lien WhatsApp fourni',
        'yes_options': ['o', 'oui'],
        'no_options': ['n', 'non'],
        # PDF Template Translations
        'cash_configuration': 'CONFIGURATION CAISSE',
        'device_configuration': 'Configuration de l\'Appareil',
        'installation_instructions': 'Instructions d\'Installation',
        'event': 'Événement',
        'location': 'Lieu',
        'sales': 'Ventes',
        'roles': 'Rôles',
        'payment_methods': 'Méthodes de paiement',
        'no_roles_specified': 'Aucun rôle spécifié',
        'step1': '1 - Ouvrir StaffX MC',
        'step2': '2 - Cliquer sur ONBOARDING QR',
        'step3': '3 - Utiliser la caméra - et pointer vers le QR code ci-dessus',
        'step4': '4 - Se connecter avec ClientX-QR',
        'step5': '5 - Ouvrir l\'application de l\'événement sur votre smartphone',
        'step6': '6 - Ouvrir le QR de Paiement',
        'step7': '7 - Scanner avec l\'appareil de caisse - le QR code sur votre téléphone',
        'whatsapp_support': 'Vous avez des problèmes - contactez-nous via WhatsApp',
        'whatsapp_support_detail': 'et envoyez-nous une vidéo ou photo du problème',
        # Terminal Interface Translations
        'cache_cleared': 'Cache Python effacé et modules rechargés',
        'cache_warning': 'Avertissement: Le nettoyage du cache a rencontré un problème',
        'cache_continue': 'Cela n\'affectera pas la fonctionnalité, continuons...',
        'testing_db': 'Test de la connectivité de la base de données...',
        'db_issue_detected': 'PROBLÈME DE CONNECTIVITÉ BASE DE DONNÉES DÉTECTÉ',
        'db_issue_message': 'L\'application peut ne pas fonctionner correctement en raison de problèmes réseau.',
        'possible_solutions': 'Solutions possibles:',
        'check_internet': '1. Vérifiez votre connexion internet',
        'check_vpn': '2. Assurez-vous que le VPN est connecté (si requis)',
        'check_aws': '3. Vérifiez si AWS RDS est accessible depuis votre emplacement',
        'contact_admin': '4. Contactez votre administrateur réseau',
        'continue_anyway': 'Voulez-vous continuer quand même? (o/n):',
        'operation_cancelled': 'Opération annulée en raison de problèmes de connectivité',
        'continuing_limited': 'Continuation avec fonctionnalité limitée...',
        'enter_tenant_slug': 'Entrez le slug du tenant:',
        'tenant_slug_required': 'Erreur: Le slug du tenant est requis',
        'process_interrupted': 'Processus interrompu par l\'utilisateur',
        'unexpected_error': 'Erreur inattendue',
        'searching_tenant': 'Recherche du tenant avec le slug',
        'domain_found': 'Domaine trouvé',
        'tenant_id_found': 'ID du tenant',
        'tenant_variable': 'Variable du tenant',
        'no_exact_match': 'Aucune correspondance exacte trouvée pour le slug',
        'similar_tenants': '{count} tenant(s) similaire(s) trouvé(s):',
        'select_option': 'Sélectionner l\'option',
        'manual_tenant_setup': 'Configuration manuelle du tenant',
        'cancel': 'Annuler',
        'operation_cancelled_user': 'Opération annulée',
        'no_similar_tenants': 'Aucun tenant similaire trouvé pour',
        'manual_setup_header': 'Configuration Manuelle du Tenant',
        'provide_tenant_info': 'Veuillez fournir les informations du tenant manuellement:',
        'enter_tenant_id': 'Entrez l\'ID du tenant:',
        'tenant_id_required': 'L\'ID du tenant est requis',
        'enter_domain': 'Entrez le domaine (ex: summercamp-2025.com):',
        'domain_required': 'Le domaine est requis',
        'domain_incomplete': 'Le domaine \'{domain}\' semble incomplet. Utiliser \'{suggested}\' à la place? (o/n):',
        'manual_setup_complete': 'Configuration manuelle du tenant terminée:',
        'db_warning': 'Avertissement: Impossible de se connecter à la base de données du tenant',
        'db_warning_message': 'Cela peut causer des problèmes lors de la récupération des QR d\'intégration',
        'continue_anyway_question': 'Continuer quand même? (o/n):',
        'db_accessible': 'Base de données du tenant \'{db}\' est accessible',
        'language_selection': 'Sélection de la Langue',
        'available_languages': 'Langues disponibles:',
        'select_language': 'Sélectionnez la langue',
        'selected_language': 'Langue sélectionnée',
        'retrieving_qrs': 'Récupération des QR d\'intégration pour le tenant',
        'qrs_found': '{count} QR d\'intégration trouvé(s)',
        'available_qrs': 'QR d\'Intégration Disponibles',
        'location': 'Lieu',
        'sales': 'Ventes',
        'event': 'Événement',
        'roles': 'Rôles',
        'payment_methods': 'Méthodes de paiement',
        'qr_code': 'Code QR',
        'template_options': 'Options de Modèle',
        'app_onboarding_qr': '1. QR d\'Intégration d\'Application',
        'guest_onboarding_qr': '2. QR d\'Intégration d\'Utilisateur Invité',
        'select_template': 'Sélectionnez le type de modèle (1 ou 2):',
        'enter_1_or_2': 'Entrez 1 ou 2',
        'enter_valid_number': 'Entrez un numéro valide',
        'generating_app_qrs': 'Génération des codes QR d\'Intégration d\'Application...',
        'multipage_pdf_generated': 'PDF multi-pages généré',
        'contains_pages': 'Contient {count} pages de QR d\'intégration',
        'whatsapp_qr_added': 'Code QR WhatsApp ajouté',
        'error_generating_pdf': 'Erreur lors de la génération du PDF QR multi-pages',
        'generating_guest_qrs': 'Génération des codes QR d\'Intégration d\'Utilisateur Invité...',
        'searching_user_data': 'Recherche de données utilisateur basée sur les noms d\'intégration...',
        'user_found': 'Utilisateur trouvé pour',
        'no_user_found': 'Aucun utilisateur trouvé pour',
        'expected_email': 'email attendu',
        'multipage_guest_pdf': 'PDF multi-pages invité généré',
        'guest_qr_pages': 'Contient {count} pages de QR invité',
        'error_generating_guest_pdf': 'Erreur lors de la génération du PDF QR invité multi-pages',
        'import_file_created': 'Fichier d\'importation créé pour {count} utilisateurs manquants',
        'fill_user_data': 'Remplissez les données utilisateur et redémarrez le processus une fois prêt',
        'import_file_generated': 'Fichier d\'importation créé',
        'fill_missing_info': 'Veuillez remplir les informations utilisateur manquantes et sauvegarder le fichier',
        'missing_dependency': 'Dépendance manquante',
        'install_requirements': 'Veuillez exécuter: pip install -r requirements.txt',
        'critical_error': 'Erreur critique',
        'check_config': 'Veuillez vérifier votre configuration et réessayer',
        # Overview Page Translations
        'event_label': 'ÉVÉNEMENT:',
        'start_label': 'Début:',
        'end_label': 'Fin:',
        'refund_start_label': 'Début Remboursement:',
        'refund_end_label': 'Fin Remboursement:',
        'total_configurations': 'TOTAL CONFIGURATIONS:',
        'name_header': 'NOM',
        'roles_header': 'RÔLES',
        'payment_header': 'PAIEMENT',
        'location_header': 'LIEU',
        'status_header': 'STATUT',
        'user_header': 'UTILISATEUR'
    },
    'es': {
        'configuration_overview': 'RESUMEN DE CONFIGURACIÓN',
        'user_overview': 'RESUMEN DE USUARIOS',
        'page': 'Página',
        'of': 'de',
        'user_configuration': 'CONFIGURACIÓN DE USUARIO',
        'currency_configuration': 'CONFIGURACIÓN DE MONEDA',
        'topup_manual': 'MANUAL DE RECARGA',
        'whatsapp_group': 'Configuración del Grupo WhatsApp',
        'has_whatsapp': '¿Hay un grupo de WhatsApp para este evento? (s/n):',
        'enter_whatsapp': 'Introduce el enlace del grupo WhatsApp:',
        'whatsapp_set': 'Grupo WhatsApp configurado:',
        'no_whatsapp': 'No hay grupo WhatsApp configurado',
        'no_whatsapp_link': 'No se proporcionó enlace WhatsApp',
        'yes_options': ['s', 'si', 'sí'],
        'no_options': ['n', 'no'],
        # PDF Template Translations
        'cash_configuration': 'CONFIGURACIÓN DE CAJA',
        'device_configuration': 'Configuración del Dispositivo',
        'installation_instructions': 'Instrucciones de Instalación',
        'event': 'Evento',
        'location': 'Ubicación',
        'sales': 'Ventas',
        'roles': 'Roles',
        'payment_methods': 'Métodos de pago',
        'no_roles_specified': 'No se especificaron roles',
        'step1': '1 - Abrir StaffX MC',
        'step2': '2 - Hacer clic en ONBOARDING QR',
        'step3': '3 - Usar cámara - y apuntar al código QR de arriba',
        'step4': '4 - Iniciar sesión con ClientX-QR',
        'step5': '5 - Abrir la aplicación del evento en tu smartphone',
        'step6': '6 - Abrir el QR de Pago',
        'step7': '7 - Escanear con el dispositivo de caja - el código QR en tu teléfono',
        'whatsapp_support': 'Tienes problemas - contáctanos vía WhatsApp',
        'whatsapp_support_detail': 'y envíanos un video o foto del problema',
        # Terminal Interface Translations
        'cache_cleared': 'Cache de Python limpiado y módulos recargados',
        'cache_warning': 'Advertencia: La limpieza de cache encontró un problema',
        'cache_continue': 'Esto no afectará la funcionalidad, continuando...',
        'testing_db': 'Probando conectividad de base de datos...',
        'db_issue_detected': 'PROBLEMA DE CONECTIVIDAD DE BASE DE DATOS DETECTADO',
        'db_issue_message': 'La aplicación puede no funcionar correctamente debido a problemas de red.',
        'possible_solutions': 'Posibles soluciones:',
        'check_internet': '1. Verifica tu conexión a internet',
        'check_vpn': '2. Asegúrate de que la VPN esté conectada (si es requerida)',
        'check_aws': '3. Verifica si AWS RDS es accesible desde tu ubicación',
        'contact_admin': '4. Contacta a tu administrador de red',
        'continue_anyway': '¿Quieres continuar de todos modos? (s/n):',
        'operation_cancelled': 'Operación cancelada debido a problemas de conectividad',
        'continuing_limited': 'Continuando con funcionalidad limitada...',
        'enter_tenant_slug': 'Introduce el slug del tenant:',
        'tenant_slug_required': 'Error: El slug del tenant es requerido',
        'process_interrupted': 'Proceso interrumpido por el usuario',
        'unexpected_error': 'Error inesperado',
        'searching_tenant': 'Buscando tenant con slug',
        'domain_found': 'Dominio encontrado',
        'tenant_id_found': 'ID del tenant',
        'tenant_variable': 'Variable del tenant',
        'no_exact_match': 'No se encontró coincidencia exacta para el slug',
        'similar_tenants': '{count} tenant(s) similar(es) encontrado(s):',
        'select_option': 'Seleccionar opción',
        'manual_tenant_setup': 'Configuración manual del tenant',
        'cancel': 'Cancelar',
        'operation_cancelled_user': 'Operación cancelada',
        'no_similar_tenants': 'No se encontraron tenants similares para',
        'manual_setup_header': 'Configuración Manual del Tenant',
        'provide_tenant_info': 'Por favor proporciona la información del tenant manualmente:',
        'enter_tenant_id': 'Introduce el ID del tenant:',
        'tenant_id_required': 'El ID del tenant es requerido',
        'enter_domain': 'Introduce el dominio (ej: summercamp-2025.com):',
        'domain_required': 'El dominio es requerido',
        'domain_incomplete': 'El dominio \'{domain}\' parece incompleto. ¿Usar \'{suggested}\' en su lugar? (s/n):',
        'manual_setup_complete': 'Configuración manual del tenant completada:',
        'db_warning': 'Advertencia: No se pudo conectar a la base de datos del tenant',
        'db_warning_message': 'Esto puede causar problemas al recuperar QR de incorporación',
        'continue_anyway_question': '¿Continuar de todos modos? (s/n):',
        'db_accessible': 'Base de datos del tenant \'{db}\' es accesible',
        'language_selection': 'Selección de Idioma',
        'available_languages': 'Idiomas disponibles:',
        'select_language': 'Selecciona idioma',
        'selected_language': 'Idioma seleccionado',
        'retrieving_qrs': 'Recuperando QRs de incorporación para el tenant',
        'qrs_found': '{count} QR(s) de incorporación encontrado(s)',
        'available_qrs': 'QRs de Incorporación Disponibles',
        'location': 'Ubicación',
        'sales': 'Ventas',
        'event': 'Evento',
        'roles': 'Roles',
        'payment_methods': 'Métodos de pago',
        'qr_code': 'Código QR',
        'template_options': 'Opciones de Plantilla',
        'app_onboarding_qr': '1. QR de Incorporación de Aplicación',
        'guest_onboarding_qr': '2. QR de Incorporación de Usuario Invitado',
        'select_template': 'Selecciona tipo de plantilla (1 o 2):',
        'enter_1_or_2': 'Introduce 1 o 2',
        'enter_valid_number': 'Introduce un número válido',
        'generating_app_qrs': 'Generando códigos QR de Incorporación de Aplicación...',
        'multipage_pdf_generated': 'PDF de múltiples páginas generado',
        'contains_pages': 'Contiene {count} páginas de QR de incorporación',
        'whatsapp_qr_added': 'Código QR de WhatsApp añadido',
        'error_generating_pdf': 'Error al generar PDF QR de múltiples páginas',
        'generating_guest_qrs': 'Generando códigos QR de Incorporación de Usuario Invitado...',
        'searching_user_data': 'Buscando datos de usuario basados en nombres de incorporación...',
        'user_found': 'Usuario encontrado para',
        'no_user_found': 'No se encontró usuario para',
        'expected_email': 'email esperado',
        'multipage_guest_pdf': 'PDF de múltiples páginas de invitado generado',
        'guest_qr_pages': 'Contiene {count} páginas de QR de invitado',
        'error_generating_guest_pdf': 'Error al generar PDF QR de invitado de múltiples páginas',
        'import_file_created': 'Archivo de importación creado para {count} usuarios faltantes',
        'fill_user_data': 'Completa los datos de usuario y reinicia el proceso una vez listo',
        'import_file_generated': 'Archivo de importación creado',
        'fill_missing_info': 'Por favor completa la información de usuario faltante y guarda el archivo',
        'missing_dependency': 'Dependencia faltante',
        'install_requirements': 'Por favor ejecuta: pip install -r requirements.txt',
        'critical_error': 'Error crítico',
        'check_config': 'Por favor verifica tu configuración e inténtalo de nuevo',
        # Overview Page Translations
        'event_label': 'EVENTO:',
        'start_label': 'Inicio:',
        'end_label': 'Fin:',
        'refund_start_label': 'Inicio Reembolso:',
        'refund_end_label': 'Fin Reembolso:',
        'total_configurations': 'TOTAL CONFIGURACIONES:',
        'name_header': 'NOMBRE',
        'roles_header': 'ROLES',
        'payment_header': 'PAGO',
        'location_header': 'UBICACIÓN',
        'status_header': 'ESTADO',
        'user_header': 'USUARIO'
    }
}

# Error Messages
ERROR_MESSAGES = {
    'no_tenant': "Tenant niet gevonden. Controleer de slug en probeer opnieuw.",
    'no_qrs': "Geen onboarding QR codes gevonden voor deze tenant.",
    'database_error': "Database verbinding mislukt. Controleer je instellingen.",
    'pdf_generation_error': "Fout bij het genereren van PDF. Probeer opnieuw."
}

# Success Messages
SUCCESS_MESSAGES = {
    'tenant_found': " Tenant gevonden en gevalideerd",
    'qrs_loaded': " Onboarding QR codes geladen", 
    'pdf_generated': " PDF succesvol gegenereerd",
    'whatsapp_added': " WhatsApp QR code toegevoegd",
    'cache_cleared': " Cache opgeschoond"
}

# File Settings
IMPORT_FILE_NAME = "missing_users_import.csv"
